### ISSUE TITLE
looks interesting, want to help add features; but can't even run it

### ISSUE THREAD

**Issue by georgejecook** [Pouja/jira-terminal#2]
ugh... obviously tired. Problem in chair; not in your code :D

**Comment by Pouja** [comment]
Haha no problem, let me know if I can help in anyway :)

**Comment by georgejecook** [comment]
Actually. How do I run it from the source?

**Comment by Pouja** [comment]
Either make the file `bin/jira-terminal` an executable or you have to alter `src/Cli.js` that it invokes the `start` function by default when executing `node src/Cli.js`.
